import { 
  FileText, 
  Music, 
  Film, 
  Table, 
  BookOpen, 
  Terminal, 
  Image, 
  Code, 
  Database, 
  Gamepad2, 
  Globe, 
  Box, 
  Map, 
  Puzzle, 
  Type, 
  Cog, 
  Settings, 
  Lock, 
  HardDrive, 
  Save, 
  File,
  FileQuestion
} from 'lucide-react';

// Category definitions matching FileInfo.org
export const categoryDefinitions = {
  text: { name: 'Text', icon: FileText, color: 'blue' },
  audio: { name: 'Audio', icon: Music, color: 'green' },
  video: { name: 'Video', icon: Film, color: 'red' },
  spreadsheet: { name: 'Spreadsheet', icon: Table, color: 'emerald' },
  ebook: { name: 'eBook', icon: BookOpen, color: 'purple' },
  executable: { name: 'Executable', icon: Terminal, color: 'orange' },
  image: { name: 'Images', icon: Image, color: 'cyan' },
  developer: { name: 'Developer Files', icon: Code, color: 'indigo' },
  database: { name: 'Database Files', icon: Database, color: 'yellow' },
  game: { name: 'Game Files', icon: Gamepad2, color: 'pink' },
  web: { name: 'Web Files', icon: Globe, color: 'teal' },
  cad: { name: 'CAD Files', icon: Box, color: 'slate' },
  gis: { name: 'GIS Files', icon: Map, color: 'lime' },
  plugin: { name: 'Plugin Files', icon: Puzzle, color: 'violet' },
  font: { name: 'Font Files', icon: Type, color: 'amber' },
  system: { name: 'System Files', icon: Cog, color: 'gray' },
  settings: { name: 'Settings Files', icon: Settings, color: 'stone' },
  encoded: { name: 'Encoded Files', icon: Lock, color: 'rose' },
  disk: { name: 'Disk Images', icon: HardDrive, color: 'sky' },
  backup: { name: 'Backup Files', icon: Save, color: 'emerald' },
  data: { name: 'Data Files', icon: File, color: 'neutral' },
  misc: { name: 'Misc Files', icon: FileQuestion, color: 'zinc' },
};

export type FileCategory = keyof typeof categoryDefinitions;

// Map file extensions to categories
export const extensionToCategory: Record<string, FileCategory> = {
  // Text
  'txt': 'text',
  'doc': 'text',
  'docx': 'text',
  'rtf': 'text',
  'odt': 'text',
  'tex': 'text',
  'wpd': 'text',
  'md': 'text',
  'markdown': 'text',
  'log': 'text',
  'msg': 'text',
  'pages': 'text',
  'wps': 'text',
  
  // Audio
  'mp3': 'audio',
  'wav': 'audio',
  'flac': 'audio',
  'aac': 'audio',
  'ogg': 'audio',
  'wma': 'audio',
  'm4a': 'audio',
  'opus': 'audio',
  'aiff': 'audio',
  'ape': 'audio',
  'alac': 'audio',
  'mid': 'audio',
  'midi': 'audio',
  'amr': 'audio',
  'ac3': 'audio',
  'dts': 'audio',
  'mka': 'audio',
  'ra': 'audio',
  'au': 'audio',
  
  // Video
  'mp4': 'video',
  'avi': 'video',
  'mkv': 'video',
  'mov': 'video',
  'wmv': 'video',
  'flv': 'video',
  'webm': 'video',
  'm4v': 'video',
  'mpg': 'video',
  'mpeg': 'video',
  '3gp': 'video',
  '3g2': 'video',
  'f4v': 'video',
  'vob': 'video',
  'ogv': 'video',
  'mts': 'video',
  'm2ts': 'video',
  'ts': 'video',
  'asf': 'video',
  'rm': 'video',
  'rmvb': 'video',
  'divx': 'video',
  'xvid': 'video',
  
  // Spreadsheet
  'xls': 'spreadsheet',
  'xlsx': 'spreadsheet',
  'xlsm': 'spreadsheet',
  'xlsb': 'spreadsheet',
  'ods': 'spreadsheet',
  'csv': 'spreadsheet',
  'tsv': 'spreadsheet',
  'numbers': 'spreadsheet',
  'gnumeric': 'spreadsheet',
  'xlr': 'spreadsheet',
  
  // eBook
  'epub': 'ebook',
  'mobi': 'ebook',
  'azw': 'ebook',
  'azw3': 'ebook',
  'pdf': 'ebook', // Can be document or ebook
  'fb2': 'ebook',
  'lit': 'ebook',
  'pdb': 'ebook',
  'lrf': 'ebook',
  'cbr': 'ebook',
  'cbz': 'ebook',
  'cbt': 'ebook',
  'djvu': 'ebook',
  
  // Executable
  'exe': 'executable',
  'msi': 'executable',
  'app': 'executable',
  'deb': 'executable',
  'rpm': 'executable',
  'dmg': 'executable',
  'pkg': 'executable',
  'apk': 'executable',
  'ipa': 'executable',
  'jar': 'executable',
  'run': 'executable',
  'com': 'executable',
  'bat': 'executable',
  'cmd': 'executable',
  'sh': 'executable',
  'bash': 'executable',
  'ps1': 'executable',
  'vbs': 'executable',
  'scr': 'executable',
  'gadget': 'executable',
  
  // Images
  'jpg': 'image',
  'jpeg': 'image',
  'png': 'image',
  'gif': 'image',
  'bmp': 'image',
  'svg': 'image',
  'webp': 'image',
  'ico': 'image',
  'tiff': 'image',
  'tif': 'image',
  'psd': 'image',
  'raw': 'image',
  'heif': 'image',
  'heic': 'image',
  'avif': 'image',
  'jfif': 'image',
  'pjpeg': 'image',
  'pjp': 'image',
  'eps': 'image',
  'ai': 'image',
  'xcf': 'image',
  'cdr': 'image',
  'nef': 'image',
  'cr2': 'image',
  'orf': 'image',
  'arw': 'image',
  'dng': 'image',
  'rw2': 'image',
  
  // Developer Files
  'js': 'developer',
  'jsx': 'developer',
  'tsx': 'developer',
  'py': 'developer',
  'java': 'developer',
  'c': 'developer',
  'cpp': 'developer',
  'cs': 'developer',
  'h': 'developer',
  'hpp': 'developer',
  'php': 'developer',
  'rb': 'developer',
  'go': 'developer',
  'rs': 'developer',
  'swift': 'developer',
  'kt': 'developer',
  'scala': 'developer',
  'r': 'developer',
  'lua': 'developer',
  'pl': 'developer',
  'sql': 'developer',
  'html': 'developer',
  'css': 'developer',
  'scss': 'developer',
  'sass': 'developer',
  'less': 'developer',
  'vue': 'developer',
  'json': 'developer',
  'xml': 'developer',
  'yaml': 'developer',
  'yml': 'developer',
  'toml': 'developer',
  'ini': 'developer',
  'conf': 'developer',
  'config': 'developer',
  'gitignore': 'developer',
  'dockerignore': 'developer',
  'editorconfig': 'developer',
  'eslintrc': 'developer',
  'prettierrc': 'developer',
  'babelrc': 'developer',
  
  // Database Files
  'db': 'database',
  'sqlite': 'database',
  'sqlite3': 'database',
  'mdb': 'database',
  'accdb': 'database',
  'dbf': 'database',
  'sdf': 'database',
  'fdb': 'database',
  'gdb': 'database',
  'ibd': 'database',
  'myd': 'database',
  'myi': 'database',
  'frm': 'database',
  'odb': 'database',
  'nsf': 'database',
  'fp7': 'database',
  'fp5': 'database',
  'fmp12': 'database',
  
  // Game Files
  'sav': 'game',
  'gam': 'game',
  'rom': 'game',
  'nes': 'game',
  'smc': 'game',
  'gba': 'game',
  'nds': 'game',
  '3ds': 'game',
  'cia': 'game',
  'xbe': 'game',
  'iso': 'game', // Can also be disk image
  'wad': 'game',
  'pak': 'game',
  'vpk': 'game',
  'mpq': 'game',
  'sc2replay': 'game',
  'dem': 'game',
  'mcworld': 'game',
  'mcpack': 'game',
  'world': 'game',
  'map': 'game',
  'bsp': 'game',
  
  // Web Files
  'htm': 'web',
  'xhtml': 'web',
  'mhtml': 'web',
  'asp': 'web',
  'aspx': 'web',
  'jsp': 'web',
  'jspx': 'web',
  'cfm': 'web',
  'cfc': 'web',
  'url': 'web',
  'webloc': 'web',
  'website': 'web',
  'webarchive': 'web',
  'download': 'web',
  'crdownload': 'web',
  'part': 'web',
  'partial': 'web',
  
  // CAD Files
  'dwg': 'cad',
  'dxf': 'cad',
  'stp': 'cad',
  'step': 'cad',
  'iges': 'cad',
  'igs': 'cad',
  'stl': 'cad',
  'obj': 'cad',
  'fbx': 'cad',
  'dae': 'cad',
  'blend': 'cad',
  'max': 'cad',
  'maya': 'cad',
  'mb': 'cad',
  'skp': 'cad',
  'vwx': 'cad',
  'rvt': 'cad',
  'rfa': 'cad',
  'ifc': 'cad',
  'nwd': 'cad',
  'nwc': 'cad',
  
  // GIS Files
  'shp': 'gis',
  'kml': 'gis',
  'kmz': 'gis',
  'gpx': 'gis',
  'geojson': 'gis',
  'topojson': 'gis',
  'osm': 'gis',
  'gml': 'gis',
  'mxd': 'gis',
  'qgs': 'gis',
  'qgz': 'gis',
  'tab': 'gis',
  'shx': 'gis',
  'prj': 'gis',
  'sbn': 'gis',
  'sbx': 'gis',
  'cpg': 'gis',
  
  // Plugin Files
  'dll': 'plugin',
  'so': 'plugin',
  'dylib': 'plugin',
  'vst': 'plugin',
  'vst3': 'plugin',
  'aax': 'plugin',
  'component': 'plugin',
  'plugin': 'plugin',
  'bundle': 'plugin',
  'xll': 'plugin',
  'addin': 'plugin',
  'xla': 'plugin',
  'xlam': 'plugin',
  'ppa': 'plugin',
  'ppam': 'plugin',
  'crx': 'plugin',
  'xpi': 'plugin',
  'safariextz': 'plugin',
  
  // Font Files
  'ttf': 'font',
  'otf': 'font',
  'woff': 'font',
  'woff2': 'font',
  'eot': 'font',
  'fon': 'font',
  'fnt': 'font',
  'pfb': 'font',
  'pfm': 'font',
  'afm': 'font',
  'vfb': 'font',
  'cff': 'font',
  'pfa': 'font',
  'sfd': 'font',
  'dfont': 'font',
  
  // System Files
  'sys': 'system',
  'drv': 'system',
  'vxd': 'system',
  'cpl': 'system',
  'cur': 'system',
  'ani': 'system',
  'icns': 'system',
  'lnk': 'system',
  'pif': 'system',
  'inf': 'system',
  'cat': 'system',
  'manifest': 'system',
  'pol': 'system',
  'msc': 'system',
  'msp': 'system',
  'msu': 'system',
  'diagcab': 'system',
  'cabinet': 'system',
  
  // Settings Files
  'plist': 'settings',
  'reg': 'settings',
  'cfg': 'settings',
  'prefs': 'settings',
  'properties': 'settings',
  'rc': 'settings',
  'ora': 'settings',
  'opt': 'settings',
  'cnf': 'settings',
  'def': 'settings',
  'theme': 'settings',
  'msstyles': 'settings',
  'clr': 'settings',
  
  // Encoded Files
  'enc': 'encoded',
  'aes': 'encoded',
  'gpg': 'encoded',
  'pgp': 'encoded',
  'asc': 'encoded',
  'sig': 'encoded',
  'p7s': 'encoded',
  'p7m': 'encoded',
  'p12': 'encoded',
  'pfx': 'encoded',
  'cer': 'encoded',
  'crt': 'encoded',
  'der': 'encoded',
  'pem': 'encoded',
  'key': 'encoded',
  'pub': 'encoded',
  'ppk': 'encoded',
  'csr': 'encoded',
  'jks': 'encoded',
  'keystore': 'encoded',
  'kdb': 'encoded',
  
  // Disk Images
  'img': 'disk',
  'ima': 'disk',
  'vhd': 'disk',
  'vhdx': 'disk',
  'vdi': 'disk',
  'vmdk': 'disk',
  'qcow': 'disk',
  'qcow2': 'disk',
  'hdd': 'disk',
  'hds': 'disk',
  'toast': 'disk',
  'sparseimage': 'disk',
  'sparsebundle': 'disk',
  'wim': 'disk',
  'swm': 'disk',
  'esd': 'disk',
  
  // Backup Files
  'bak': 'backup',
  'backup': 'backup',
  'bkp': 'backup',
  'bkf': 'backup',
  'abk': 'backup',
  'gho': 'backup',
  'v2i': 'backup',
  'tib': 'backup',
  'vbk': 'backup',
  'vrb': 'backup',
  'vib': 'backup',
  'spf': 'backup',
  'dsa': 'backup',
  'asd': 'backup',
  'wbk': 'backup',
  'xlk': 'backup',
  'bck': 'backup',
  'bcm': 'backup',
  'tmp': 'backup',
  'temp': 'backup',
  
  // Data Files
  'dat': 'data',
  'data': 'data',
  'save': 'data',
  'rdata': 'data',
  'mat': 'data',
  'sas7bdat': 'data',
  'dta': 'data',
  'por': 'data',
  'sas': 'data',
  'xpt': 'data',
  'h5': 'data',
  'hdf5': 'data',
  'nc': 'data',
  'cdf': 'data',
  'fits': 'data',
  'grib': 'data',
  'bufr': 'data',
  
  // Archive files (move some to compressed/archive category)
  'zip': 'backup',
  'rar': 'backup',
  '7z': 'backup',
  'tar': 'backup',
  'gz': 'backup',
  'bz2': 'backup',
  'xz': 'backup',
  'z': 'backup',
  'lz': 'backup',
  'lzma': 'backup',
  'cab': 'backup',
  'arc': 'backup',
  'arj': 'backup',
  'lha': 'backup',
  'lzh': 'backup',
  'ace': 'backup',
  'uue': 'backup',
  'uu': 'backup',
  'xxe': 'backup',
  'zoo': 'backup',
  'sit': 'backup',
  'sitx': 'backup',
};

// Helper function to get category for a file extension
export function getFileCategory(extension: string): FileCategory {
  const ext = extension.toLowerCase().replace('.', '');
  return extensionToCategory[ext] || 'misc';
}